export const projects = [
  {
    "title": "E-Commerce Startup Estados Unidos",
    "description": "Plataforma de comercio electrónico completa desarrollada con Next.js (App Router) que incluye panel de administración, gestión de inventario, procesamiento de pagos con Square, autenticación con JWT y control de roles, además de servicios de correo y utilidades operativas (p. ej. tracking).",
    "image": "/img/ecommerce.png",
    "technologies": [
      "Next.js",
      "React",
      "TypeScript",
      "PostgreSQL",
      "Prisma",
      "Tailwind CSS",
      "Square Payments",
      "Autenticación JWT",
      "Roles y permisos",
      "Zustand",
      "Zod",
      "Cloudflare Turnstile",
      "Sentry"
    ],
    "features": [
      "Carrito de compras y flujo de checkout",
      "Panel de administración (productos, categorías, usuarios, ofertas/descuentos, impuestos, etc.)",
      "Integración de pagos con Square",
      "Gestión de inventario y catálogo de productos",
      "Autenticación y autorización (JWT + roles)",
      "Notificaciones/correos transaccionales (reset password, confirmaciones, etc.)",
      "Carga de imágenes/archivos",
      "Tracking e integraciones operativas (UPS)"
    ],
    "github": "#",
    "demo": "https://test-ecom.internationalfood360.com/",
    "status": "En Desarrollo"
  },
  {
    title: "GJ TWO THOUSAND | Executive Car & Limousine Service",
    description:
      "Sitio web de transporte ejecutivo y de lujo (NYC, NJ y CT) con reservas, cálculo de tarifas, dashboard autenticado y gestión de usuarios/facturas con generación de PDF y envío por correo.",
    image: "/img/transport.png",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Prisma 7",
      "PostgreSQL",
      "Tailwind CSS 4",
      "Zod",
      "Nodemailer (Zoho Mail)",
      "jsPDF + jsPDF-AutoTable",
      "Cloudflare Turnstile",
      "Zustand",
      "SWR",
      "Jest + Testing Library"
    ],
    features: [
      "Sistema de reservas (formulario /reservation) con notificación por correo (reservation@gjtwothousand.com)",
      "Páginas de servicios: Airport, Hourly Chauffeur, Corporate Travel, Point-to-Point, Private Jet & FBO",
      "Módulo de tarifas (Rates) con calculadora y tarifas Out-of-Town/Manhattan basadas en data JSON",
      "Autenticación (login) y recuperación de contraseña con OTP",
      "Dashboard autenticado (secciones de usuarios, facturas e incrementos)",
      "Gestión de usuarios con roles (admin, banker, customer) y datos de asistente",
      "Generación de facturas PDF y envío por correo",
      "Formulario de contacto con notificación por correo",
      "SEO técnico: sitemap, robots, OpenGraph y datos estructurados (StructuredData)"
    ],
    github: "#",
    demo: "https://gjtwothousand.com/",
    status: "Completado"
  },
  {
    "title": "Compre360 – Soluciones Digitales y E-commerce",
    "description": "Plataforma de soluciones digitales con e-commerce premium, showroom digital, marca personal, autenticación, panel administrativo con RBAC, suscripciones, facturación electrónica DIAN y chat en tiempo real.",
    "image": "/img/compre360.png",
    "technologies": [
      "Next.js 16",
      "TypeScript",
      "React 19",
      "Prisma 7",
      "PostgreSQL",
      "Tailwind CSS 4",
      "Zustand",
      "SWR",
      "Zod",
      "React Hook Form",
      "Framer Motion",
      "JWT (jose/jsonwebtoken)",
      "bcrypt",
      "Nodemailer",
      "@react-pdf/renderer",
      "Google APIs (Drive)",
      "Cloudflare Turnstile",
      "Vitest"
    ],
    "features": [
      "E-commerce Premium con gestión de inventario y productos",
      "Showroom Digital de catálogos y galerías",
      "Página de Marca Personal con demo interactivo",
      "Sistema de autenticación con JWT, bcrypt y recuperación de contraseña",
      "Chat en tiempo real con streaming y calificación",
      "Panel administrativo con RBAC (admin, super_admin, viewer)",
      "Gestión de usuarios, servicios, proyectos, contratos y suscripciones",
      "Suscripciones recurrentes con panel para viewer y actualización por cron",
      "Facturación electrónica DIAN (XML firmado, CUFE, ZIP, SOAP)",
      "Pagos integrados con ePayco y Square (webhooks)",
      "Cola de emails transaccionales con reintentos y panel de jobs",
      "Generación de PDFs (contratos y facturas) con @react-pdf/renderer",
      "Notificaciones por correo (bienvenida, servicio agregado, suscripción vencida)",
      "Protección anti-bots con Cloudflare Turnstile",
      "Dashboard analítico con métricas y filtros por cliente",
      "Internacionalización (ES/EN) con selector de idioma",
      "SEO con sitemap, robots, JSON-LD y Open Graph",
      "Suite de tests con Vitest (unit e integración)"
    ],
    "services": [
      "E-commerce Premium",
      "Showroom Digital",
      "Marca Personal",
      "Páginas Institucionales",
      "Desarrollo a Medida"
    ],
    "integrations": [
      "PostgreSQL (Prisma ORM)",
      "ePayco (pagos online Colombia)",
      "Square (pagos internacionales)",
      "DIAN (facturación electrónica Colombia)",
      "Google Drive (almacenamiento)",
      "Nodemailer / SMTP (emails)",
      "Cloudflare Turnstile (CAPTCHA)"
    ],
    "github": "#",
    "demo": "https://compre360.com",
    "status": "Completado",
  }
];